language: node_js
node_js:
- '10'
dist: trusty
sudo: required
env:
- CHANGE_MINIKUBE_NONE_USER=true
addons:
  firefox: latest
  chrome: stable
services:
- docker
cache:
  directories:
  - node_modules
install:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- npm install
before_script:
- npm run lint
- npm run build
- kubectl --kubeconfig="ozark-www-kubeconfig.yaml" get nodes
- kubectl apply -f service.yml
- kubectl apply -f deployment.yml
script:
- xvfb-run npm run test
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker build -t $DOCKERHUB_USERNAME/ozark-www .
- docker push $DOCKERHUB_USERNAME/ozark-www:latest
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_de5aa8f11a37_key -iv $encrypted_de5aa8f11a37_iv
  -in ozark-www-kubeconfig.yaml.enc -out ozark-www-kubeconfig.yaml -d
