language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  firefox: latest
  chrome: stable
services:
  - docker
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
  - npm run build
script:
  - xvfb-run npm run test
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD 
  - docker build -t $DOCKERHUB_USERNAME/ozark-www .
  - docker push $DOCKERHUB_USERNAME/ozark-www:latest
notifications:
  email: false



